### ISSUE TITLE
error when starting the backendserver

### ISSUE THREAD

**Issue by sirmalware** [rewanthtammana/Damn-Vulnerable-Bank#10]
I get this error when I try to start the backendserver 

`(node:320460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:320460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
user@Latitude:~/Damn-Vulnerable-Bank/BackendServer$ 
online results say its something about not adding catch blocks to where promises are used. maybe issue is depricated packages?

**Comment by rewanthtammana** [comment]
Hi @sirmalware , How are you trying to run the backend server? With docker or without docker? Can you please try to run it with Docker?

Backend server installation steps are mentioned here: [Install Backend Server](https://github.com/rewanthtammana/Damn-Vulnerable-Bank/tree/master/BackendServer)

**Comment by sirmalware** [comment]
ive tried running it with both docker-compose and npm to know avail but both give the same errors. to reproduce could you clone the current repo and try running the server would like to confirm its not just on my side. and yes I've read the instructions couple 10x times now marvelously written btw.

**Comment by rewanthtammana** [comment]
I just tried it online on [Katacoda](https://www.katacoda.com/courses/docker/deploying-first-container). It's working for me. See the last few lines.

![image](https://user-images.githubusercontent.com/22347290/149659255-696483a8-a246-471e-9098-1f8445059688.png)

**Comment by sirmalware** [comment]
![Screenshot from 2022-01-16 15-10-38](https://user-images.githubusercontent.com/55733240/149659414-1dfbac21-340e-4382-ad50-69e6302f05b9.png)
 by the screenshot what could be wrong

**Comment by rewanthtammana** [comment]
Okay, I understood your concern. We have two docker containers as part of [BackendServer](https://github.com/rewanthtammana/Damn-Vulnerable-Bank/blob/master/BackendServer/docker-compose.yml).
1. API 
2. MySQL

As mentioned [here](https://github.com/rewanthtammana/Damn-Vulnerable-Bank/blob/master/BackendServer/docker-compose.yml#L10), API container depends on MySQL container.

Until MySQL server is not up, API server tries to connect with MySQL but the connection will not be successful. The API server will throw some errors. Because of it, the API server container will be terminated. A new API server container will be created immediately to retry the same request.

Just run `docker-compose up --build` & wait for some time. Then the MySQL container will be fully functional & so will the API server. Don't press `Ctrl+C`, just wait for a while.

**Comment by sirmalware** [comment]
ok. have you tried npm start locally tho?

**Comment by rewanthtammana** [comment]
Not required, if you are using docker.

**Comment by hafiz-ng** [comment]
Hi rewanthtammana,

`npm start` on local machine doesn't work. 

You should probably take a look at this error message:

`(node:53570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by rewanthtammana** [comment]
@hafiz-ng It might be an issue with the version of npm you are using. Try running it using docker. It's preferred for installation & easy to create/destroy resources. [Instructions here](https://github.com/rewanthtammana/Damn-Vulnerable-Bank/tree/master/BackendServer)

**Comment by hafiz-ng** [comment]
Thanks. I will just that.

**Comment by hafiz-ng** [comment]
Thanks. I will try that.
