### ISSUE TITLE
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

### ISSUE THREAD

**Issue by srand2** [rewanthtammana/Damn-Vulnerable-Bank#11]
Im using genymotion.

when I install the app I'm recieving this error
```Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]```

any ideas.

Even if I drop the app directly it errors out.

**Comment by rewanthtammana** [comment]
How are you installing? Can you share more information?
