### ISSUE TITLE
Unable to setup in Genymotion Emulator

### ISSUE THREAD

**Issue by rajraman786** [rewanthtammana/Damn-Vulnerable-Bank#14]
After installing the dvba.apk in genymotion error is showing 
Please view the ss

![Screenshot from 2023-01-04 22-25-02](https://user-images.githubusercontent.com/55931033/210738075-b57c2944-8837-46e3-98f9-d73885bcae64.png)

**Comment by rewanthtammana** [comment]
@rajraman786 It's because the app isn't allowed to run on emulators like genymotion, memu, etc. You will need bypass the checks that block the installation on emulator to use it further.

If you feel stuck, refer to this guide: https://rewanthtammana.com/damn-vulnerable-bank/index.html
