### ISSUE TITLE
Process crashed: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by delmarocks** [rewanthtammana/Damn-Vulnerable-Bank#16]
Any solution regarding about this? When I try to login or signup the app crashes automatically.

Here's a screenshot of the errors 
![Screenshot_2023-06-29-23-57-06-250_com termux](https://github.com/rewanthtammana/Damn-Vulnerable-Bank/assets/31096473/8793d0cb-39e4-4303-9461-47b81dc31be3)

**Comment by rewanthtammana** [comment]
@delmarocks I don't think this is related to the app. Maybe its an issue with the emulator. Can you try using a different one or with a different version of image?
