### ISSUE TITLE
device dont see the backend IP

### ISSUE THREAD

**Issue by andrey-yalta** [rewanthtammana/Damn-Vulnerable-Bank#9]
hello, i am running backend server on my computer, but device dont sea the IP, can you help me?

**Comment by rewanthtammana** [comment]
There are two cases here:
1. If you are running backend server on local computer, then you need to make sure both your mobile & computer are using the same wifi to ensure both are on same network
2. If you are running backend server on cloud providers, then you need to make sure the firewall rule is opened for the port to be accessible by other users.

Try them and let us know if you are still facing the issue
